config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    passwords: 'public/passwords',
    sessions: 'public/sessions'
  }
  namespace :public do
    get 'homes/about'
    get '/post_images/search' => 'searches#search'
    get '/post_images/search_place' => 'post_images#search_place', as: 'search_place'
    get '/post_images/search_tag' => 'post_images#search_tag', as: 'search_tag'
    resources :post_images, only: [:index, :new, :edit, :update, :create, :destroy, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update]
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end


  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :tags, only: [:index, :edit, :create, :destroy, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :posting_tags
  has_many :post_images, through: :posting_tags

  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["post_images", "posting_tags"]
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      @tags = Tag.all
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path(@tag.id)
    else
      render :edit
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<%= form_with model: @tag, url: admin_tag_path do |f| %>
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block m-4 ml-5 bg-light">　タグ編集　</h5>
        <table class="table table-sm table-borderless">
          <tr>
            <td class="pr-5"><%= f.label "タグ名" %></td>
            <td class="pr-5"><%= f.text_field :name %></td>
            <td class="pr-5"><%= f.submit "　変更を保存　", class: "d-inline-block btn btn-success rounded btn-sm mx-auto" %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/tags/index.html.erb
<% if @tag.errors.any? %>
  <%= @tag.errors.count %>件のエラーが発生しました
  <ul>
    <% @tag.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @tag, url: admin_tags_path do |f| %>
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block m-4 ml-5 bg-light">　タグ一覧・追加　</h5>
        <table class="table table-sm table-borderless">
          <tr>
            <td class="pr-5"><%= "タグ名" %></td>
            <td class="pr-5"><%= f.text_field :name %></td>
            <td class="pr-5"><%= f.submit "　新規登録　", class: "d-inline-block btn btn-success rounded btn-sm mx-auto" %></td>
          </tr>
        </table>
        <table class="table col-md-8 mt-5">
          <thead class="bg-light">
            <tr>
              <th>タグ</th>
              <th><br></th>
            </tr>
          </thead>
            <tbody>
              <% @tags.each do |tag| %>
                <tr>
                  <td>
                    <%= tag.name %>
                  </td>
                  <td>
                    <%= link_to "　編集する　", edit_admin_tag_path(tag.id), class: "btn btn-success btn-sm rounded" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>