config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    passwords: 'public/passwords',
    sessions: 'public/sessions'
  }
  namespace :public do
    get 'homes/about'
    get '/post_images/search' => 'searches#search'
    get '/post_images/search_place' => 'post_images#search_place', as: 'search_place'
    get '/post_images/search_tag' => 'post_images#search_tag', as: 'search_tag'
    resources :post_images, only: [:index, :new, :edit, :update, :create, :destroy, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update]
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end


  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :tags, only: [:index, :edit, :create, :destroy, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  enum way_of_getting: { buy: 0, receive: 1 }

  enum prefecture: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :posting_tags
  has_many :tags, through: :posting_tags

  validates :name, presence: true
  validates :my_comment, presence: true
  validates :way_of_getting, presence: true

  def self.create_all_ranks
     @all_ranks = PostImage.find(Bookmark.group(:post_image_id).order('count(post_image_id) desc').limit(3).pluck(:post_image_id))
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["comment", "created_at", "id", "name", "prefecture", "price", "updated_at", "user_id", "way_of_getting"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["bookmarks", "image_attachment", "image_blob", "post_comments", "posting_tags", "tags", "user"] #アソシエーション先を記述
  end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @post_images = PostImage.page(params[:page]).per(9)
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    @post_image = PostImage.find(params[:id])
    if @post_image.update(post_image_params)
      @post_image.tags.destroy_all
      tag_ids =  params[:post_image][:tag_ids]
      tag_ids.shift
      tag_ids.each do |id|
        PostingTag.create(post_image_id: @post_image.id, tag_id: id)
      end

      redirect_to admin_post_image_path(@post_image.id)
    else
      render :edit
    end
  end

  def show
    @post_image = PostImage.find(params[:id])
    @user = User.find(@post_image.user.id)
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to admin_post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:image, :name, :my_comment, :way_of_getting, :price, :prefecture, :user_id, :tag_ids)
  end
end

app/helpers/admin/post_images_helper.rb
module Admin::PostImagesHelper
end

app/views/admin/post_images/edit.html.erb
<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <ul>
    <% @post_image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post_image, url: admin_post_image_path(@post_image.id), method: :patch do |f| %>
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="col-md-10 offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block m-4 ml-5 bg-light">　投稿編集　</h5>
      <div class="col-md-8 offset-md-2">
        <table class="table table-sm table-borderless">
           <tr>
            <td><%= f.label "おみやげ画像" %></td>
            <td><br></td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label "おみやげ名" %></td>
            <td><br></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label "コメント" %></td>
            <td><br></td>
            <td><%= f.text_area :my_comment %></td>
          </tr>
          <tr>
            <td><%= f.label "旅先" %></td>
            <td><br></td>
            <td><%= f.select :prefecture, User.prefectures.keys, {} %></td>
          </tr>
          <tr>
            <td><%= f.label "入手方法" %></td>
            <td><br></td>
            <td>
              <%= f.radio_button :way_of_getting, :buy %>
              <%= f.label :way_of_getting_buy, "買った" %>
              <%= f.radio_button :way_of_getting, :receive %>
              <%= f.label :way_of_getting_receive, "もらった" %>
            </td>
          </tr>
          <tr>
            <td><%= f.label "価格" %></td>
            <td><br></td>
            <td><%= f.text_field :price %>円</td>
          </tr>
          <tr>
            <td><%= f.label "タグ" %></td>
            <td><br></td>
            <td>
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                <%= tag.label do %>
                  <%= tag.check_box %>
                  <%= tag.text %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><br></td>
            <td><br></td>
            <td><%= f.submit "変更を保存", class: "btn btn-success rounded btn-sm d-grid gap-2 col-8 mx-auto" %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/post_images/index.html.erb
<%= form_with model: @post_image, url: admin_post_images_path do |f| %>
<div class="container-fluid">
  <div class="row">
    <div class="offset-md-2">
      <h5 class="d-inline-block ml-5 my-4 bg-light">　投稿一覧　</h5>
    </div>
    <table class="table col-8 offset-2 mb-5">
      <thead class="bg-light">
        <tr>
          <th>投稿ID</th>
          <th col="2">おみやげ名</th>
          <th></br></th>
          <th>画像</th>
          <th col="2">タグ</th>
          <th>投稿者</th>
          <th>投稿時間</th>
          <th><br></th>
        </tr>
      </thead>
      <tbody>
        <% @post_images.each do |post_image| %>
          <tr>
            <td><%= post_image.id %></td>
            <td col="2">
              <%= post_image.name %>
            </td>
            <td></br></td>
            <td><%= image_tag post_image.get_image(40, 30) %></td>
            <td col="2">
              <% post_image.tags.each do |tag| %>
                <%= tag.name %>
              <% end %>
            </td>
            <td><%= post_image.user.name %></td>
            <td><%= post_image.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to "詳細", admin_post_image_path(post_image.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

<%= paginate @post_images %>

app/views/admin/post_images/show.html.erb
<% if @post_image.errors.any? %>
  <%= @post_image.errors.count %>件のエラーが発生しました
  <ul>
    <% @post_image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container mt-5">
  <%= form_with model: @post_image, url: admin_post_image_path do |f| %>
  <div class="row">
    <div class="col-md-4">
      <p><%= image_tag @post_image.get_image(400, 300) %></p>
      <div class="text-right">
        投稿者:
          <%= @post_image.user.name %>
      </div>
    </div>

    <div class="col-md-4 offset-md-1">
      <div class="post-content">
        <div class="row">
          <div class="col-md-5">
            <p class="strong h4"><%= @post_image.name %></p>
          </div>
          <div class="col-md-5">
            <p><%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
          </div>
        </div>
        <div class="row">
          <div class="mr-auto ml-3"><%= @post_image.bookmarks.count %>件のブックマーク</div>
        </div>
        <table class="table table-borderless">
          <tr>
            <td>旅先</td>
            <td><%= @post_image.prefecture %></td>
          </tr>
          <tr>
            <td>コメント</td>
            <td><%= @post_image.my_comment %></td>
          </tr>
          <tr>
            <td>入手方法</td>
            <td><%= @post_image.way_of_getting_i18n %></td>
          </tr>
          <% if @post_image.price.present? %>
          <tr>
            <td>価格</td>
            <td><%= @post_image.price.to_s(:delimited) %>円</td>
          </tr>
          <% end %>
          <tr class="text-secondary">
            <td>タグ</td>
            <td>
              <% @post_image.tags.each do |tag| %>
             　<%= tag.name %>
              <%end%>
            </td>
          </tr>
        </table>
        <div>
            <%= link_to "管理者編集", edit_admin_post_image_path(@post_image), class: "btn btn-outline-secondary btn-block rounded mt-3" %>
            <%= link_to "管理者削除", admin_post_image_path, method: :delete, class: "btn btn-outline-danger btn-block rounded mt-3", "data-confirm" => "本当に削除しますか？" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row mt-5">
    <div class="comment-title h5"><strong>コメント</strong>(<%= @post_image.post_comments.count %>件)</div>
  </div>
  <% @post_image.post_comments.each do |post_comment| %>
    <div class="row">
      <div class="col-md-2">
        <%=image_tag post_comment.user.get_profile_image(50, 50) %>
        <p><%= post_comment.user.name %></p>
      </div>
      <div class="col-md-6">
        <p><%= post_comment.comment %></p>
        <div class="text-right"><%= post_comment.created_at.strftime('%Y/%m/%d') %></div>
      </div>
      <div class="col-md-2">
        <div class="d-md-flex justify-content-md-end"></div>
          <%= link_to "管理者削除", admin_post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete,
          class: "btn btn-outline-danger btn-block rounded mt-3", "data-confirm" => "本当に削除しますか？"%>
      </div>
    </div>
  <% end %>
  <div class="row mt-3">
    <%= form_with model: [@post_image, @post_comment], url: public_post_image_post_comments_path(@post_image.id) do |f| %>
      <div class="message-box mx-3"><%= f.text_area :comment, class: "form-control", style: "width:100%", rows: '5', placeholder: "コメント" %>
      <%= f.submit "送信する", class: "btn btn-success btn-block rounded small mt-2 mb-5" %></div>
    <% end %>
  </div>
</div>