config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    passwords: 'public/passwords',
    sessions: 'public/sessions'
  }
  namespace :public do
    get 'homes/about'
    get '/post_images/search' => 'searches#search'
    get '/post_images/search_place' => 'post_images#search_place', as: 'search_place'
    get '/post_images/search_tag' => 'post_images#search_tag', as: 'search_tag'
    resources :post_images, only: [:index, :new, :edit, :update, :create, :destroy, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update]
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end


  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :tags, only: [:index, :edit, :create, :destroy, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :birth_year, presence: true
  validates :birth_month, presence: true

  enum gender: {male: 0, female: 1, others: 2}

  enum prefecture: {
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.birth_year = 1990
      user.birth_month = 12
      user.id = 6
    end
  end

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end




end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @user = User.page(params[:page]).per(9)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:profile_image, :name, :email, :prefecture, :gender, :birth_year, :birth_month, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="col-md-10 offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block m-4 ml-5 bg-light">　プロフィール編集　</h5>
      <div class="col-md-8 offset-md-2">
        <table class="table table-sm table-borderless">
           <tr>
            <td><%= f.label "プロフィール画像" %></td>
            <td><br></td>
            <td><%= f.file_field :profile_image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label "メールアドレス" %></td>
            <td><br></td>
            <td><%= f.email_field :email, autocomplete: "email" %></td>
          </tr>
          <tr>
            <td><%= f.label "会員名" %></td>
            <td><br></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label "お住まいの都道府県" %></td>
            <td><br></td>
            <td><%= f.select :prefecture, User.prefectures.keys, {} %></td>
          </tr>
          <tr>
            <td><%= f.label "性別" %></td>
            <td><br></td>
            <td>
              <%= f.radio_button :gender, User.genders.key(0) %>
              <%= f.label :gender_male, User.genders_i18n[:male] %>
              <%= f.radio_button :gender, User.genders.key(1) %>
              <%= f.label :gender_female, User.genders_i18n[:female] %>
              <%= f.radio_button :gender, User.genders.key(2) %>
              <%= f.label :gender_others, User.genders_i18n[:others] %>
            </td>
          </tr>
          <tr>
            <td><%= f.label "生年月" %></td>
            <td><br></td>
            <td>
              <%= f.select :birth_year, *[1940..2023], :include_blank => "年" %>
              <%= f.select :birth_month, *[1..12], :include_blank => "月" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.label "会員ステータス" %>
            </td>
            <td><br></td>
            <td>
              <%= f.radio_button :is_deleted, false %>有効
              <%= f.radio_button :is_deleted, true %>無効
            </td>
          </tr>
          <tr>
            <td><br></td>
            <td><br></td>
            <td><%= f.submit "変更を保存", class: "btn btn-success rounded btn-sm d-grid gap-2 col-8 mx-auto" %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/users/index.html.erb
<%= form_with model: @user, url: admin_users_path do |f| %>
<div class="container-fluid">
  <div class="row">
    <div class="offset-md-1">
      <h5 class="d-inline-block m-4 ml-5 bg-light">　会員一覧　</h5>
    </div>
  </div>
  <div class="row　justify-content-center">
    <div class="mx-auto col-md-8 col-md-offset-2 ">
        <table class="table">
          <thead class="bg-light">
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
              <th><br></th>
            </tr>
          </thead>
            <tbody>
              <% @user.each do |user| %>
                <tr>
                  <td>
                    <%= user.id %>
                  </td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    <%= user.email %>
                  </td>
                  <td>
                    <%= user.is_deleted? ? '無効' : '有効' %>
                  </td>
                  <td>
                    <%= link_to "詳細", admin_user_path(user.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
      </div>
  </div>
</div>
<% end %>

<%= paginate @user %>

app/views/admin/users/show.html.erb
<%= form_with model: @user, url: admin_user_path do |f| %>
<div class="container px-5 px-sm-0 mt-3">
  <div class="row">
    <div class="offset-md-1 pb-5 mb-5">
      <h5 class="d-inline-block my-4 bg-light">　<%= @user.name %>さんの会員詳細　</h5>
      <table class="table table-sm table-borderless">
        <tr>
          <td><%= f.label "会員ID" %></td>
          <td><%= @user.id %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "プロフィール画像" %></td>
          <td><%= image_tag @user.get_profile_image(100, 100) %></td>
        </tr>
        <tr>
          <td><%= f.label "名前" %></td>
          <td><%= @user.name %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "メールアドレス" %></td>
          <td><%= @user.email %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "お住まいの都道府県" %></td>
          <td><%= @user.prefecture %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "性別" %></td>
          <td><%= @user.gender_i18n %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "生年月" %></td>
          <td><%= @user.birth_year %>年<%= @user.birth_month %>月</td>
          <td><br></td>
        </tr>
        <tr>
          <td><%= f.label "会員ステータス" %></td>
          <td><%= @user.is_deleted? ? '無効' : '有効' %></td>
          <td><br></td>
        </tr>
        <tr>
          <td><br></td>
          <td><%= link_to "編集する", edit_admin_user_path, class: "btn btn-success rounded btn-sm mx-auto" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<% end %>