config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    passwords: 'public/passwords',
    sessions: 'public/sessions'
  }
  namespace :public do
    get 'homes/about'
    get '/post_images/search' => 'searches#search'
    get '/post_images/search_place' => 'post_images#search_place', as: 'search_place'
    get '/post_images/search_tag' => 'post_images#search_tag', as: 'search_tag'
    resources :post_images, only: [:index, :new, :edit, :update, :create, :destroy, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update]
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
  end


  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :tags, only: [:index, :edit, :create, :destroy, :update]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_images, only: [:index, :show, :edit, :update, :destroy] do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oshimiyage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/1309c48d16.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="top-header bg-info">
      <nav class="navbar navbar-expand-lg navbar-light p-1">
        <div class="container">
          <a class="navbar-brand text-light p-3" href="/">推みやげ</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "おみやげ一覧", public_post_images_path, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_public_post_image_path, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "地域から探す", public_search_place_path, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "タグから探す", public_search_tag_path, class: 'nav-link small ml-2' %>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "マイページ", public_user_path(current_user.id), class: 'nav-link small ml-2' %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", admin_post_images_path, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_users_path, class: 'nav-link small ml-2' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "このサイトについて", public_homes_about_path, class: 'nav-link small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "ゲストログイン", public_users_guest_sign_in_path, method: :post, class: 'nav-link text-primary small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規会員登録", new_user_registration_path, class: 'nav-link text-primary small ml-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-primary small ml-2' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <header class="head bg-info">
    <div class="container">
      <div class="row">
        <div class="mx-auto mb-3"><%= render 'public/shared/search', q: @q %></div>
        <%= flash.now[:notice] %>
      </div>
    </div>
  </header>
  <main class="mb-auto">
    <%= yield %>
  </main>
  <footer class="bg-dark text-white pt-5 pb-4">

  </footer>
  </body>
</html>